CREATE TABLE estado (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    nome_estado VARCHAR2(50 CHAR) NOT NULL,
    uf VARCHAR2(2 CHAR) NOT NULL,
    CONSTRAINT pk_estado PRIMARY KEY (id),
    CONSTRAINT uk_estado_nome UNIQUE (nome_estado),
    CONSTRAINT uk_estado_uf UNIQUE (uf)
);

CREATE TABLE cidade (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    nome_cidade VARCHAR2(100 CHAR) NOT NULL,
    id_estado NUMBER(19) NOT NULL,
    CONSTRAINT pk_cidade PRIMARY KEY (id),
    CONSTRAINT uk_cidade_nome_estado UNIQUE (nome_cidade, id_estado),
    CONSTRAINT fk_cidade_estado FOREIGN KEY (id_estado) REFERENCES estado (id)
);

CREATE TABLE usuario (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    nome_real VARCHAR2(100 CHAR) NOT NULL,
    nome_anonimo VARCHAR2(50 CHAR),
    data_nascimento DATE NOT NULL,
    celular VARCHAR2(20 CHAR),
    senha VARCHAR2(255 CHAR) NOT NULL,
    data_cadastro DATE NOT NULL,
    id_cidade NUMBER(19) NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT uk_usuario_celular UNIQUE (celular),
    CONSTRAINT fk_usuario_cidade FOREIGN KEY (id_cidade) REFERENCES cidade (id)
);

CREATE TABLE tb_ajudante (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    area_atuacao VARCHAR2(100 CHAR) NOT NULL,
    motivacao CLOB,
    disponivel NUMBER(1) DEFAULT 0 NOT NULL,
    rating FLOAT(53),
    CONSTRAINT pk_ajudante PRIMARY KEY (id),
    CONSTRAINT ck_ajudante_disp CHECK (disponivel IN (0, 1)),
    CONSTRAINT ck_ajudante_rating CHECK (rating IS NULL OR (rating >= 0 AND rating <= 5))
);

CREATE TABLE chat (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    id_usuario NUMBER(19) NOT NULL,
    id_ajudante NUMBER(19) NOT NULL,
    data_inicio TIMESTAMP(6) NOT NULL,
    data_fim TIMESTAMP(6),
    status VARCHAR2(40 CHAR) NOT NULL,
    CONSTRAINT pk_chat PRIMARY KEY (id),
    CONSTRAINT fk_chat_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id),
    CONSTRAINT fk_chat_ajudante FOREIGN KEY (id_ajudante) REFERENCES tb_ajudante (id),
    CONSTRAINT ck_chat_status CHECK (status IN (
        'INICIADO',
        'EM_ANDAMENTO',
        'FINALIZADO_USUARIO',
        'FINALIZADO_AJUDANTE',
        'FINALIZADO_SISTEMA'
    )),
    CONSTRAINT ck_chat_data_fim CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);

CREATE TABLE tb_mensagem (
    id_mensagem NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    id_chat NUMBER(19) NOT NULL,
    id_remetente NUMBER(19) NOT NULL,
    texto VARCHAR2(1000 CHAR) NOT NULL,
    data_envio TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_mensagem PRIMARY KEY (id_mensagem),
    CONSTRAINT fk_mensagem_chat FOREIGN KEY (id_chat) REFERENCES chat (id),
    CONSTRAINT fk_mensagem_remetente FOREIGN KEY (id_remetente) REFERENCES usuario (id)
);
