CREATE TABLE tb_admin_account (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(120 CHAR) NOT NULL,
    senha VARCHAR2(255 CHAR) NOT NULL,
    data_atualizacao TIMESTAMP(6),
    CONSTRAINT pk_admin_account PRIMARY KEY (id),
    CONSTRAINT uk_admin_account_username UNIQUE (username)
);
