-- Padronizacao corporativa de nomenclatura para tabelas, colunas, constraints e indexes.
-- Mantem historico Flyway: V1..V4 permanecem intactas e esta versao faz a migracao segura.

-- 1) Padronizacao de nomes de tabela (prefixo TB_)
RENAME estado TO TB_ESTADO;
RENAME cidade TO TB_CIDADE;
RENAME usuario TO TB_USUARIO;
RENAME chat TO TB_CHAT;

-- 2) Padronizacao de nomes de coluna por dominio
ALTER TABLE TB_ESTADO RENAME COLUMN id TO ID_ESTADO;
ALTER TABLE TB_ESTADO RENAME COLUMN nome_estado TO NM_ESTADO;
ALTER TABLE TB_ESTADO RENAME COLUMN uf TO SG_ESTADO;

ALTER TABLE TB_CIDADE RENAME COLUMN id TO ID_CIDADE;
ALTER TABLE TB_CIDADE RENAME COLUMN nome_cidade TO NM_CIDADE;

ALTER TABLE TB_USUARIO RENAME COLUMN id TO ID_USUARIO;
ALTER TABLE TB_USUARIO RENAME COLUMN nome_real TO NM_USUARIO_REAL;
ALTER TABLE TB_USUARIO RENAME COLUMN nome_anonimo TO NM_USUARIO_ANONIMO;
ALTER TABLE TB_USUARIO RENAME COLUMN data_nascimento TO DT_NASCIMENTO;
ALTER TABLE TB_USUARIO RENAME COLUMN celular TO NR_CELULAR;
ALTER TABLE TB_USUARIO RENAME COLUMN senha TO DS_SENHA;
ALTER TABLE TB_USUARIO RENAME COLUMN data_cadastro TO DT_CADASTRO;

ALTER TABLE TB_AJUDANTE RENAME COLUMN id TO ID_AJUDANTE;
ALTER TABLE TB_AJUDANTE RENAME COLUMN area_atuacao TO NM_AREA_ATUACAO;
ALTER TABLE TB_AJUDANTE RENAME COLUMN login TO NM_LOGIN;
ALTER TABLE TB_AJUDANTE RENAME COLUMN senha TO DS_SENHA;
ALTER TABLE TB_AJUDANTE RENAME COLUMN motivacao TO DS_MOTIVACAO;
ALTER TABLE TB_AJUDANTE RENAME COLUMN disponivel TO FL_DISPONIVEL;
ALTER TABLE TB_AJUDANTE RENAME COLUMN rating TO NR_RATING;

ALTER TABLE TB_CHAT RENAME COLUMN id TO ID_CHAT;
ALTER TABLE TB_CHAT RENAME COLUMN data_inicio TO DH_INICIO;
ALTER TABLE TB_CHAT RENAME COLUMN data_fim TO DH_FIM;
ALTER TABLE TB_CHAT RENAME COLUMN status TO ST_CHAT;

ALTER TABLE TB_MENSAGEM RENAME COLUMN id_remetente TO ID_USUARIO_REMETENTE;
ALTER TABLE TB_MENSAGEM RENAME COLUMN id_remetente_ajudante TO ID_AJUDANTE_REMETENTE;
ALTER TABLE TB_MENSAGEM RENAME COLUMN texto TO TX_MENSAGEM;
ALTER TABLE TB_MENSAGEM RENAME COLUMN data_envio TO DH_ENVIO;

ALTER TABLE TB_ADMIN_ACCOUNT RENAME COLUMN id TO ID_ADMIN_ACCOUNT;
ALTER TABLE TB_ADMIN_ACCOUNT RENAME COLUMN username TO NM_LOGIN;
ALTER TABLE TB_ADMIN_ACCOUNT RENAME COLUMN senha TO DS_SENHA;
ALTER TABLE TB_ADMIN_ACCOUNT RENAME COLUMN data_atualizacao TO DH_ATUALIZACAO;

-- 3) Padronizacao de nomes de constraints
ALTER TABLE TB_ESTADO RENAME CONSTRAINT pk_estado TO PK_TB_ESTADO;
ALTER TABLE TB_ESTADO RENAME CONSTRAINT uk_estado_nome TO UK_TB_ESTADO_NM_EST;
ALTER TABLE TB_ESTADO RENAME CONSTRAINT uk_estado_uf TO UK_TB_ESTADO_SG_EST;

ALTER TABLE TB_CIDADE RENAME CONSTRAINT pk_cidade TO PK_TB_CIDADE;
ALTER TABLE TB_CIDADE RENAME CONSTRAINT uk_cidade_nome_estado TO UK_TB_CIDADE_NM_ID_ESTADO;
ALTER TABLE TB_CIDADE RENAME CONSTRAINT fk_cidade_estado TO FK_TB_CIDADE_ID_EST;

ALTER TABLE TB_USUARIO RENAME CONSTRAINT pk_usuario TO PK_TB_USUARIO;
ALTER TABLE TB_USUARIO RENAME CONSTRAINT uk_usuario_celular TO UK_TB_USUARIO_NR_CEL;
ALTER TABLE TB_USUARIO RENAME CONSTRAINT fk_usuario_cidade TO FK_TB_USUARIO_ID_CID;

ALTER TABLE TB_AJUDANTE RENAME CONSTRAINT pk_ajudante TO PK_TB_AJUDANTE;
ALTER TABLE TB_AJUDANTE RENAME CONSTRAINT ck_ajudante_disp TO CK_TB_AJUDANTE_FL_DISP;
ALTER TABLE TB_AJUDANTE RENAME CONSTRAINT ck_ajudante_rating TO CK_TB_AJUDANTE_NR_RAT;
ALTER TABLE TB_AJUDANTE RENAME CONSTRAINT uk_ajudante_login TO UK_TB_AJUDANTE_NM_LOGIN;

ALTER TABLE TB_CHAT RENAME CONSTRAINT pk_chat TO PK_TB_CHAT;
ALTER TABLE TB_CHAT RENAME CONSTRAINT fk_chat_usuario TO FK_TB_CHAT_ID_USUARIO;
ALTER TABLE TB_CHAT RENAME CONSTRAINT fk_chat_ajudante TO FK_TB_CHAT_ID_AJUDANTE;
ALTER TABLE TB_CHAT RENAME CONSTRAINT ck_chat_status TO CK_TB_CHAT_ST_CHAT;
ALTER TABLE TB_CHAT RENAME CONSTRAINT ck_chat_data_fim TO CK_TB_CHAT_DH_FIM;

ALTER TABLE TB_MENSAGEM RENAME CONSTRAINT pk_mensagem TO PK_TB_MENSAGEM;
ALTER TABLE TB_MENSAGEM RENAME CONSTRAINT fk_mensagem_chat TO FK_TB_MENSAGEM_ID_CHAT;
ALTER TABLE TB_MENSAGEM RENAME CONSTRAINT fk_mensagem_remetente TO FK_TB_MSG_ID_USR_REM;
ALTER TABLE TB_MENSAGEM RENAME CONSTRAINT fk_mensagem_remetente_ajudante TO FK_TB_MSG_ID_AJD_REM;
ALTER TABLE TB_MENSAGEM RENAME CONSTRAINT ck_mensagem_remetente_exclusivo TO CK_TB_MSG_REM_EXCL;

ALTER TABLE TB_ADMIN_ACCOUNT RENAME CONSTRAINT pk_admin_account TO PK_TB_ADMIN_ACCOUNT;
ALTER TABLE TB_ADMIN_ACCOUNT RENAME CONSTRAINT uk_admin_account_username TO UK_TB_ADMIN_NM_LOGIN;

-- 4) Padronizacao de nomes de indexes de apoio
ALTER INDEX idx_cidade_estado RENAME TO IX_TB_CIDADE_ID_ESTADO;
ALTER INDEX idx_usuario_cidade RENAME TO IX_TB_USUARIO_ID_CIDADE;
ALTER INDEX idx_chat_usuario RENAME TO IX_TB_CHAT_ID_USUARIO;
ALTER INDEX idx_chat_ajudante RENAME TO IX_TB_CHAT_ID_AJUDANTE;
ALTER INDEX idx_chat_status RENAME TO IX_TB_CHAT_ST_CHAT;
ALTER INDEX idx_mensagem_chat_data RENAME TO IX_TB_MSG_CHAT_DH_ENV;
ALTER INDEX idx_mensagem_remetente_data RENAME TO IX_TB_MSG_USR_DH_ENV;
ALTER INDEX idx_mensagem_rem_ajudante_data RENAME TO IX_TB_MSG_AJD_DH_ENV;
