CREATE TABLE tb_admin_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(120) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    data_atualizacao TIMESTAMP(6),
    CONSTRAINT pk_admin_account PRIMARY KEY (id),
    CONSTRAINT uk_admin_account_username UNIQUE (username)
);
